

 Report 1: Customer Revenue Report

| Customer Name                                               | City | Total Orders | Total Amount Paid | Pending Amount |
| ----------------------------------------------------------- | ---- | ------------ | ----------------- | -------------- |
| Generated using SQL queries from Orders and Payments tables |      |              |                   |                |

Purpose:

* Shows customer-wise order activity.
* Identifies high-value customers.
* Tracks pending payments.



 Report 2: City Revenue Report

| City                          | Total Customers | Total Orders | Total Revenue |
| ----------------------------- | --------------- | ------------ | ------------- |
| Generated using GROUP BY city |                 |              |               |

Purpose:

* Compares sales performance across cities.
* Identifies top-performing locations.



Report 3: Product Sales Report

| Product Name                                    | Category | Quantity Sold | Revenue Generated |
| ----------------------------------------------- | -------- | ------------- | ----------------- |
| Generated using Products and Order_Items tables |          |               |                   |

Purpose:

* Identifies best-selling products.
* Measures product-wise revenue contribution.



 Report 4: Category Revenue Report

| Category                                        | Products Sold | Revenue |
| ----------------------------------------------- | ------------- | ------- |
| Generated using Products and Order_Items tables |               |         |

Purpose:

* Shows revenue generated by each product category.
* Helps identify the most profitable category.



 Report 5: Payment Status Report

| Order ID                                   | Customer Name | Payment Mode | Payment Status | Amount |
| ------------------------------------------ | ------------- | ------------ | -------------- | ------ |
| Generated using Orders and Payments tables |               |              |                |        |

Purpose:

* Tracks successful, pending, and failed payments.
* Helps monitor payment processing.



 Report 6: Delivery Status Report

| Order ID                                     | Customer Name | Delivery Partner | Delivery Status | Delivery City |
| -------------------------------------------- | ------------- | ---------------- | --------------- | ------------- |
| Generated using Orders and Deliveries tables |               |                  |                 |               |

Purpose:

* Monitors order deliveries.
* Tracks pending and completed deliveries.


 KEY INSIGHTS FROM REPORTS

1. Revenue Analysis

   * Revenue can be analyzed by customer, city, and category.
   * Electronics category contributes the highest revenue.

2. Customer Analysis

   * Frequent customers generate a major share of revenue.
   * Customers with multiple orders can be identified easily.

3. Product Analysis

   * Best-selling products can be identified using quantity sold.
   * Unsold products can be tracked for inventory planning.

4. Payment Analysis

   * Paid, pending, and failed payments are monitored.
   * Orders without payment records can be identified.

5. Delivery Analysis

   * Delivered, pending, and cancelled orders can be tracked.
   * Delivery performance can be evaluated effectively.
